### ISSUE TITLE
Issue publishing mqtt message to nocan

### ISSUE THREAD

**Issue by alphalove** [omzlo/nocanc#2]
Hello,
Firstly, fantastic project, thankyou!

I'm sure I'm doing something obvious wrong, but can't seem to work it out.  I'm trying to pick up the MQTT topic nocan1/led/set and bridge that to nocan channel 'led1'.  I tried the following nocanc.exe config rule.

[[mqtt.subscribers]]
topic="nocan1/led/set"
channel="led1"

I run nocan.exe mqtt (on widows 10), and get the following error when publishing a payload to MQTT topic nocan1/let/set (from a simple node-red inject).

 _INFO Closing connection to 192.168.0.47:1883: Received PUBLISH packet without topic_

I've successfully done the reverse i.e. bridged the nocan channel led1 to MQTT topci nocan1/led using the following config.

[[mqtt.publishers]]
channel="led1"
topic="nocan1/led"

With this I see the MQTT nocan1/led topic and payload change when I change the value via nocanc webui control page.

Any pointers as to what I am doing wrong?

Thanks in advance,

alex

**Comment by omzlo** [comment]
Hopefully this issue is now fixed in nocanc 0.2.3 -- reopen otherwise. 

For a full discussion of this issue please see:
https://forum.omzlo.com/forum/nocan/mqtt-subscribers-packet-without-topic-issue
